version: "3.9"
services:
  timescaledb:
    image: timescale/timescaledb:latest-pg12
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    volumes:
      - timescaledb-data:/var/lib/postgresql/data
volumes:
  timescaledb-data: